apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-cleanup
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-container
            image: busybox:1.36
            command: ["sh", "-c", "echo 'CronJob heartbeat'"]
          restartPolicy: OnFailure
