apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-cleanup
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-container
            image: {{ .Values.cronjob.image | quote }}
            command: ["sh", "-c", "echo 'CronJob heartbeat'"]
          restartPolicy: OnFailure
