apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-ds
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ds
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ds
    spec:
      containers:
        - name: busybox-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: {{ .Values.image.command | toJson }}
          # --- זה החלק של סעיף 5 ---
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
            - secretRef:
                name: {{ .Release.Name }}-secret