apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-init-job
spec:
  template:
    spec:
      containers:
      - name: job-container
        image: busybox:1.36
        command: ["sh", "-c", "echo 'Job executed successfully at $(date)'"]
      restartPolicy: Never
