# --- General Settings ---
replicaCount: 2

# --- Image Settings ---
image:
  repository: motinet/helm-app
  

# --- Application Configuration ---
appConfig:
  message: "Hello from Moti Levi's BusyBox"
  apiToken: "MySecretToken123"

# --- Service Settings ---
service:
  type: ClusterIP
  port: 80

# שים לב לשינוי כאן: nginx נמצא ברמה הכי חיצונית (בלי רווחים לפניו)
# וכל מה שמתחתיו מוסט פנימה ב-2 רווחים
nginx:
  image:
    repository: motinet/helm-app
    tag: latest
  service:
    type: NodePort
    ports:
      http: 80
  persistence:
    enabled: false

  # Configuration for the Nginx dependency
  nginx:
  image:
    repository: motinet/helm-app
    tag: latest
  service:
    type: NodePort
    ports:
      http: 80   # מוודא שהסרוויס מאזין בפורט 80
  persistence:
    enabled: false
    
# --- cronjob Settings ---
cronjob:
  schedule: "*/1 * * * *"
  image: "busybox"

# --- job Settings --
job:
  image: "busybox"