# --- General Settings ---
replicaCount: 2

# --- Application Configuration ---
appConfig:
  message: "Hello from Moti Levi's BusyBox"
  apiToken: "MySecretToken123"

# --- Main Service Settings ---
service:
  type: ClusterIP
  port: 80

# --- Nginx Dependency Settings ---
# שים לב: המילה nginx חייבת להיות צמודה להתחלה (בלי רווחים)
nginx:
  image:
    repository: motinet/helm-app
    tag: latest
    pullPolicy: Always
  service:
    type: NodePort
    ports:
      http: 80
  persistence:
    enabled: false

# --- cronjob Settings ---
cronjob:
  schedule: "*/1 * * * *"
  image: "busybox"

# --- job Settings --
job:
  image: "busybox"