# --- General Settings ---
replicaCount: 2

# --- Image Settings (עבור ה-Deployment הראשי) ---
image:
  repository: motinet/helm-app
  tag: latest
  pullPolicy: Always

# --- Application Configuration ---
appConfig:
  message: "Hello from Moti Levi's BusyBox"
  apiToken: "MySecretToken123"

# --- Main Service Settings ---
service:
  type: NodePort
  port: 80         # הפורט החיצוני של הסרוויס
  targetPort: 80   # הפורט שה-Nginx בתוך הפוד באמת מאזין לו (נסה 80, ואם לא עובד שנה ל-8080)

# --- cronjob Settings ---
cronjob:
  schedule: "*/1 * * * *"
  image: "busybox"

# --- job Settings --
job:
  image: "busybox"