# --- General Settings ---
replicaCount: 2

# --- Image Settings ---
image:
  repository: busybox
  tag: "1.37"
  pullPolicy: IfNotPresent
  # ב-Busybox צריך פקודה כדי שהקונטיינר לא יסגר מיד
  command: ["sh", "-c", "echo Hello from BusyBox && sleep 3600"]

# --- Application Configuration ---
appConfig:
  message: "Hello from Moti Levi's BusyBox"
  apiToken: "MySecretToken123"

# --- Service Settings ---
service:
  type: ClusterIP
  port: 80

  # Configuration for the Nginx dependency
nginx:
  image:
    tag: latest  # זה ימשוך תמיד את הגירסה הכי עדכנית ויפתור את בעיית ה-Pull
  service:
    type: NodePort
    ports:
      http: 80   # מוודא שהסרוויס מאזין בפורט 80
  persistence:
    enabled: false