# --- General Settings ---
replicaCount: 2

# --- Image Settings ---
image:
  repository: motinet/helm-app
  

# --- Application Configuration ---
appConfig:
  message: "Hello from Moti Levi's BusyBox"
  apiToken: "MySecretToken123"

# --- Service Settings ---
service:
  type: ClusterIP
  port: 80

  # Configuration for the Nginx dependency
nginx:
  image:
    tag: latest  # זה ימשוך תמיד את הגירסה הכי עדכנית ויפתור את בעיית ה-Pull
  service:
    type: NodePort
    ports:
      http: 80   # מוודא שהסרוויס מאזין בפורט 80
  persistence:
    enabled: false
    
# --- cronjob Settings ---
cronjob:
  schedule: "*/1 * * * *"
  image: "busybox"

# --- job Settings --
job:
  image: "busybox"