# --- General Settings ---
replicaCount: 2

# --- Image Settings (עבור ה-Deployment הראשי) ---
image:
  repository: motinet/helm-app
  tag: latest
  pullPolicy: Always

# --- Application Configuration ---
appConfig:
  message: "Hello from Moti Levi's BusyBox"
  apiToken: "MySecretToken123"

# --- Main Service Settings ---
service:
  type: ClusterIP
  port: 80

# --- Nginx Dependency Settings ---
nginx:
  image:
    repository: motinet/helm-app
    tag: latest
    pullPolicy: Always
  
  # ניטרול מנגנוני הבדיקה וההרצה המובנים של Bitnami שגורמים לשגיאה 127
  containerSecurityContext:
    enabled: false
  podSecurityContext:
    enabled: false
  
  # ביטול ניסיונות להעתיק לוגים או קבצים סטטיים מנתיבים שלא קיימים באימג' שלך
  cloneStaticSiteFromGit:
    enabled: false
  
  service:
    type: NodePort
    ports:
      http: 80
  
  persistence:
    enabled: false

# --- cronjob Settings ---
cronjob:
  schedule: "*/1 * * * *"
  image: "busybox"

# --- job Settings --
job:
  image: "busybox"